import Foundation

/// A single subtitle/caption track available for a video.
public struct Caption: Identifiable, Codable, Hashable, Sendable {
    public let languageCode: String
    public let languageName: String
    public let url: URL
    public let isAutoGenerated: Bool

    public var id: String { isAutoGenerated ? "\(languageCode)-auto" : languageCode }

    public init(
        languageCode: String,
        languageName: String,
        url: URL,
        isAutoGenerated: Bool = false
    ) {
        self.languageCode = languageCode
        self.languageName = languageName
        self.url = url
        self.isAutoGenerated = isAutoGenerated
    }
}
