import Foundation

// MARK: - /search

struct PipedSearchResponse: Decodable, Sendable {
    let items: [PipedSearchItem]
    let nextpage: String?
    let suggestion: String?
    let corrected: Bool?
}

/// A single Piped search result. Piped's `/search` endpoint returns a
/// heterogeneous mix of `"stream"`, `"channel"`, and `"playlist"` items in
/// one array, disambiguated by `type` — only `"stream"` maps to `Video`.
struct PipedSearchItem: Decodable, Sendable {
    /// e.g. "/watch?v=dQw4w9WgXcQ"
    let url: String
    /// `"stream"`, `"channel"`, or `"playlist"` in the polymorphic `/search`
    /// context. Piped's OpenAPI spec only requires this field there — when
    /// this same shape is reused for `relatedStreams` (always videos, never
    /// channels/playlists) the key is frequently absent entirely, so this
    /// must stay optional or decoding the whole array would throw.
    let type: String?
    let title: String
    let thumbnail: String?
    let uploaderName: String?
    /// e.g. "/channel/UCxxxxxxxx"
    let uploaderUrl: String?
    let uploaderAvatar: String?
    let uploaderVerified: Bool?
    /// Unix epoch milliseconds. `nil`/absent for some result types.
    let uploaded: Int64?
    /// Seconds; `-1` for livestreams.
    let duration: Int?
    let views: Int?
    let isShort: Bool?
    let shortDescription: String?
}

// MARK: - /streams/{id}

struct PipedStreamsResponse: Decodable, Sendable {
    let title: String
    let description: String?
    let uploader: String?
    let uploaderUrl: String?
    let uploaderAvatar: String?
    let uploaderVerified: Bool?
    let thumbnailUrl: String?
    let duration: Int?
    let views: Int?
    let likes: Int?
    let dislikes: Int?
    /// Master HLS playlist, present for livestreams and some VODs.
    let hls: String?
    /// DASH manifest URL. Not consumed by Module 2 — kept for forward
    /// compatibility with a future DASH-based player path.
    let dash: String?
    let livestream: Bool?
    let audioStreams: [PipedStream]?
    let videoStreams: [PipedStream]?
    let relatedStreams: [PipedSearchItem]?
    let subtitles: [PipedSubtitle]?
}

struct PipedStream: Decodable, Sendable {
    let url: String?
    let format: String?
    /// e.g. "720p60" or "128kbps"
    let quality: String?
    let mimeType: String?
    let codec: String?
    let bitrate: Int?
    let width: Int?
    let height: Int?
    let fps: Int?
    /// `true` for DASH video-only tracks; `false` for muxed/progressive.
    let videoOnly: Bool?
    let contentLength: Int64?
}

struct PipedSubtitle: Decodable, Sendable {
    let url: String?
    let mimeType: String?
    let name: String?
    let code: String?
    let autoGenerated: Bool?
}
