import Foundation

/// Parsing helpers for Piped's relative-URL conventions (e.g.
/// `/watch?v=ID`, `/channel/ID`). Deliberately kept out of `Core/Models` —
/// the domain layer shouldn't know how any particular backend encodes IDs
/// into URLs.
enum PipedURLParsing {
    static func videoID(fromWatchPath path: String) -> String? {
        guard let components = URLComponents(string: path) else { return nil }
        return components.queryItems?.first(where: { $0.name == "v" })?.value
    }

    static func channelID(fromChannelPath path: String) -> String? {
        let marker = "/channel/"
        guard let range = path.range(of: marker) else { return nil }
        let remainder = path[range.upperBound...]
        return remainder.split(separator: "/").first.map(String.init)
    }
}

extension ChannelSummary {
    init(uploaderName: String?, uploaderUrl: String?, uploaderAvatar: String?, uploaderVerified: Bool?) {
        self.init(
            id: uploaderUrl.flatMap(PipedURLParsing.channelID(fromChannelPath:)) ?? "",
            name: uploaderName ?? "Unknown",
            avatarURL: uploaderAvatar.flatMap(URL.init(string:)),
            isVerified: uploaderVerified ?? false
        )
    }
}

extension Video {
    /// Maps a Piped search/related-stream item into the domain `Video`
    /// type. Returns `nil` for non-video items (channels, playlists) so
    /// callers can `compactMap` directly over a heterogeneous results
    /// array, and for malformed items missing a parseable video ID.
    init?(pipedSearchItem item: PipedSearchItem) {
        // `type` is only ever populated as a discriminator in the polymorphic
        // `/search` results. In `relatedStreams` (and similar reused-shape
        // contexts) it's typically absent, and absent there always means
        // "this is a video" since that field never contains anything else.
        // So: explicit non-"stream" types are rejected, but a missing type
        // is treated as an implicit "stream".
        if let type = item.type, type != "stream" { return nil }
        guard let videoID = PipedURLParsing.videoID(fromWatchPath: item.url) else { return nil }

        let channel = ChannelSummary(
            uploaderName: item.uploaderName,
            uploaderUrl: item.uploaderUrl,
            uploaderAvatar: item.uploaderAvatar,
            uploaderVerified: item.uploaderVerified
        )

        let uploadDate: Date? = item.uploaded.flatMap { milliseconds in
            milliseconds > 0 ? Date(timeIntervalSince1970: Double(milliseconds) / 1000) : nil
        }

        self.init(
            id: videoID,
            title: item.title,
            thumbnailURL: item.thumbnail.flatMap(URL.init(string:)),
            channel: channel,
            duration: TimeInterval(max(item.duration ?? 0, 0)),
            viewCount: max(item.views ?? 0, 0),
            uploadDate: uploadDate,
            description: item.shortDescription ?? "",
            isShort: item.isShort ?? false
        )
    }
}

extension StreamInfo {
    init?(pipedAudioStream stream: PipedStream) {
        guard let urlString = stream.url, let url = URL(string: urlString) else { return nil }
        self.init(
            url: url,
            kind: .audio,
            mimeType: stream.mimeType ?? "audio/mp4",
            codec: stream.codec ?? "",
            qualityLabel: stream.quality ?? "",
            bitrate: stream.bitrate ?? 0,
            width: nil,
            height: nil,
            fps: nil,
            contentLength: stream.contentLength
        )
    }

    init?(pipedVideoStream stream: PipedStream) {
        guard let urlString = stream.url, let url = URL(string: urlString) else { return nil }
        self.init(
            url: url,
            kind: (stream.videoOnly ?? true) ? .video : .muxed,
            mimeType: stream.mimeType ?? "video/mp4",
            codec: stream.codec ?? "",
            qualityLabel: stream.quality ?? "",
            bitrate: stream.bitrate ?? 0,
            width: stream.width,
            height: stream.height,
            fps: stream.fps,
            contentLength: stream.contentLength
        )
    }
}

extension Caption {
    init?(pipedSubtitle subtitle: PipedSubtitle) {
        guard let urlString = subtitle.url,
              let url = URL(string: urlString),
              let code = subtitle.code else { return nil }
        self.init(
            languageCode: code,
            languageName: subtitle.name ?? code,
            url: url,
            isAutoGenerated: subtitle.autoGenerated ?? false
        )
    }
}

extension VideoDetail {
    init(videoID: String, response: PipedStreamsResponse) {
        let channel = ChannelSummary(
            uploaderName: response.uploader,
            uploaderUrl: response.uploaderUrl,
            uploaderAvatar: response.uploaderAvatar,
            uploaderVerified: response.uploaderVerified
        )

        let video = Video(
            id: videoID,
            title: response.title,
            thumbnailURL: response.thumbnailUrl.flatMap(URL.init(string:)),
            channel: channel,
            duration: TimeInterval(max(response.duration ?? 0, 0)),
            viewCount: max(response.views ?? 0, 0),
            uploadDate: nil,
            description: response.description ?? "",
            isShort: false
        )

        self.init(
            video: video,
            likeCount: response.likes,
            dislikeCount: response.dislikes,
            isLive: response.livestream ?? false,
            audioStreams: (response.audioStreams ?? []).compactMap(StreamInfo.init(pipedAudioStream:)),
            videoStreams: (response.videoStreams ?? []).compactMap(StreamInfo.init(pipedVideoStream:)),
            hlsURL: response.hls.flatMap(URL.init(string:)),
            captions: (response.subtitles ?? []).compactMap(Caption.init(pipedSubtitle:)),
            relatedVideos: (response.relatedStreams ?? []).compactMap(Video.init(pipedSearchItem:))
        )
    }
}
